"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app/JupyterNotebookLauncher.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'app/resources/app_icon/app_icon.icns',
    'plist': {
        'NSUIElement': 1,
    },
    'resources': [
        'app/resources'
    ]
}
NAME = 'Jupyter Notebook Launcher'

setup(
    app=APP,
    name=NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
